#!/usr/bin/with-contenv bash
# ─────────────────────────────────────────────────────────────────────────────
# apply-overrides.sh
# ─────────────────────────────────────────────────────────────────────────────
# s6-overlay cont-init.d drop-in. Bind-mounted into the p3terx/aria2-pro
# container as `/etc/cont-init.d/48-apply-overrides` so it runs at boot,
# AFTER the image's `28-fix` (which applies env-driven sed substitutions to
# /config/aria2.conf) and BEFORE `58-permissions` (which fixes ownership).
#
# Purpose
#   Apply a small list of repo-tracked aria2.conf overrides (most importantly
#   `force-save=true`, so AriaNg's stopped queue survives container restarts).
#   The image otherwise uses opinionated defaults that don't suit our setup —
#   see apps/aria2/README.md for the full rationale.
#
# Inputs (mounted by `apps/aria2/podman-setup.sh`)
#   /etc/aria2-overrides.conf    repo-tracked file with one `key=value` per line
#                                (host: apps/aria2/configs/local.aria2.conf.overrides)
#   /config/aria2.conf           generated by `08-config`, patched by `28-fix`
#
# Behaviour
#   - For each `key=value` line in /etc/aria2-overrides.conf, replace the
#     matching `^key=` line in /config/aria2.conf or append it.
#   - Idempotent: re-running on container restart converges to the same state.
#   - Defensive: missing override file is a no-op, not an error.
# ─────────────────────────────────────────────────────────────────────────────

# Reuse the colour/log helpers + ${ARIA2_CONF} from the image's init-base.
. /etc/init-base

OVERRIDES_FILE="/etc/aria2-overrides.conf"
TAG="apply-overrides"

if [[ ! -f "${OVERRIDES_FILE}" ]]; then
    echo -e "${INFO} ${TAG}: no overrides file at ${OVERRIDES_FILE}, nothing to apply"
    exit 0
fi

if [[ ! -f "${ARIA2_CONF}" ]]; then
    echo -e "${ERROR} ${TAG}: ${ARIA2_CONF} not found (08-config should have created it). Aborting."
    exit 1
fi

applied=0
skipped=0

while IFS= read -r line || [[ -n "$line" ]]; do
    # Strip trailing carriage returns just in case the file came from a CRLF editor.
    line="${line%$'\r'}"

    # Skip blanks and comment lines.
    [[ -z "${line// }" ]] && continue
    [[ "${line}" =~ ^[[:space:]]*# ]] && continue

    # Require `key=value` form; skip anything malformed.
    if [[ "${line}" != *=* ]]; then
        echo -e "${WARN} ${TAG}: skipping malformed line (no '='): ${line}"
        skipped=$((skipped + 1))
        continue
    fi

    key="${line%%=*}"

    # `|` is safe as the sed delimiter because aria2 option keys never contain it.
    if grep -q "^${key}=" "${ARIA2_CONF}"; then
        sed -i "s|^${key}=.*|${line}|" "${ARIA2_CONF}"
    else
        echo "${line}" >> "${ARIA2_CONF}"
    fi
    echo -e "${INFO} ${TAG}: ${line}"
    applied=$((applied + 1))
done < "${OVERRIDES_FILE}"

echo -e "${INFO} ${TAG}: applied ${applied} override(s), skipped ${skipped}"
exit 0
