# qBittorrent - Torrent Download Client
# https://docs.linuxserver.io/images/docker-qbittorrent/
#
# proxy_buffering off: Management UI with small responses.
# client_max_body_size 0: Allow torrent file uploads of any size.

server {
    listen 1080;
    server_name qbt.aevion.lan qbittorrent.aevion.lan;

    set $UPSTREAM_IP 10.0.2.2;
    set $UPSTREAM_PORT 8061;

    client_max_body_size 0;

    location / {
        proxy_pass http://$UPSTREAM_IP:$UPSTREAM_PORT;
        include /etc/nginx/snippets/proxy-defaults.conf;

        proxy_buffering off;

        proxy_set_header Referer "";
        proxy_set_header Host $http_host;
    }
}

server {
    listen 1443 ssl;
    http2 on;
    server_name qbt.aevion.lan qbittorrent.aevion.lan;

    set $UPSTREAM_IP 10.0.2.2;
    set $UPSTREAM_PORT 8061;

    client_max_body_size 0;

    include /etc/nginx/snippets/self-signed.conf;
    include /etc/nginx/snippets/ssl-params.conf;

    location / {
        proxy_pass http://$UPSTREAM_IP:$UPSTREAM_PORT;
        include /etc/nginx/snippets/proxy-defaults.conf;

        proxy_buffering off;

        proxy_set_header Referer "";
        proxy_set_header Host $http_host;
    }
}
